export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DRAFT_LIMIT_EXCEEDED: 'DRAFT_LIMIT_EXCEEDED',
  GENERATION_FAILED: 'GENERATION_FAILED',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export const DRAFT_LIMITS = {
  free: 10,
  pro: 100,
  unlimited: Infinity
} as const;

export const VARIABLE_TYPES = [
  'STRING',
  'TEXT',
  'DATE',
  'NUMBER',
  'CURRENCY',
  'SELECT',
  'MULTISELECT',
  'PHONE',
  'EMAIL'
] as const;
